--if need to clear
--DBCC SQLPERF('sys.dm_os_wait_stats', CLEAR);
WITH waitStats AS (
  SELECT
      wait_type  AS waitType,
      wait_time_ms AS waitTimeMs,
      100.0 * wait_time_ms / SUM(wait_time_ms) OVER () AS pctOfTotal
  FROM sys.dm_os_wait_stats
  WHERE wait_time_ms > 0
    AND wait_type NOT IN (
      'BROKER_EVENTHANDLER','BROKER_RECEIVE_WAITFOR','BROKER_TASK_STOP',
      'BROKER_TO_FLUSH','BROKER_TRANSMITTER','CHECKPOINT_QUEUE','CLR_AUTO_EVENT',
      'CLR_MANUAL_EVENT','DIRTY_PAGE_POLL','DISPATCHER_QUEUE_SEMAPHORE',
      'FT_IFTS_SCHEDULER_IDLE_WAIT','HADR_FILESTREAM_IOMGR_IOCOMPLETION',
      'HADR_LOGCAPTURE_WAIT','HADR_NOTIFICATION_DEQUEUE','HADR_TIMER_TASK',
      'HADR_WORK_QUEUE','LAZYWRITER_SLEEP','LOGMGR_QUEUE','ONDEMAND_TASK_QUEUE',
      'REQUEST_FOR_DEADLOCK_SEARCH','RESOURCE_QUEUE','SLEEP_TASK','SLEEP_SYSTEMTASK',
      'SQLTRACE_BUFFER_FLUSH','SQLTRACE_INCREMENTAL_FLUSH_SLEEP',
      'SQLTRACE_WAIT_ENTRIES','WAITFOR','LOGMGR_RESERVE_APPEND',
      'XE_DISPATCHER_JOIN','XE_DISPATCHER_WAIT','XE_TIMER_EVENT','SOS_WORK_DISPATCHER'
    )
)
SELECT TOP (15)
    waitType,
    waitTimeMs / 1000.0                AS waitSeconds,
    CAST(pctOfTotal AS DECIMAL(6,2))   AS pctOfTotal
FROM waitStats
ORDER BY pctOfTotal DESC;
